server.port: 9070
idp.url: https://identitytoolkit.googleapis.com/v1/accounts

spring:
  profiles:
    active: dev

  cloud.stream:
    bindings:
      output-users:
        destination: users
      output-dashboard:
        destination: dashboard
      output-newusers:
        destination: newusers
      input-newusers:
        destination: newusers

---
spring:
  profiles: dev
  data:
    mongodb:
      host: localhost
      port: 27017
      database: hourglass
  cloud.stream:
    kafka.binder:
      brokers: 127.0.0.1
      defaultBrokerPort: 9092
---
spring:
  profile: prod
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: hourglass
  cloud.stream:
    kafka.binder:
      brokers: kafka
      defaultBrokerPort: 9093

