server.port: 9070
idp.url: https://identitytoolkit.googleapis.com/v1/accounts
apiKey: "${HG_API_KEY: dummy}"

spring:
  profiles:
    active: dev

  cloud.stream:
    bindings:
      output-users:
        destination: users
      output-dashboard:
        destination: dashboard
      output-newusers:
        destination: newusers
      input-newusers:
        destination: newusers
    defaultBinder: rabbit
    default.contentType: application/json


---
spring:
  profiles: dev
  data:
    mongodb:
      host: localhost
      port: 27017
      database: hourglass
spring.rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest
service.url:
  gateway: localhost

---
spring:
  profile: prod
  data:
    mongodb:
      host: hourglassdb-service
      port: 27017
      database: hourglass
  cloud.stream:
    bindings:
      output-users:
        destination: users
      output-dashboard:
        destination: dashboard
      output-newusers:
        destination: newusers
      input-newusers:
        destination: newusers


spring.rabbitmq:
  host: rabbitmq
  port: 5672
  username: guest
  password: guest
service.url:
  gateway: gateway-service


